/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交问题并接收正文与状态流
         * @description 要求同源 Origin 和空闲的当前会话。text 是未完成预览，按消息和内容块组合；discarded 丢弃预览。done 的完整快照替换预览，禁止重复追加。
         */
        post: operations["queryChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Millis: number | null;
        PublicTurn: {
            /** Format: uuid */
            id: string | null;
            question: string;
            answer: string;
            /** @enum {unknown} */
            status: "running" | "completed" | "cancelled" | "failed";
            failureReason: string;
            startedAt: string;
            completedAt: string;
        };
        ModelTiming: {
            id: number | null;
            started_ms: components["schemas"]["Millis"];
            first_token_ms: components["schemas"]["Millis"];
            first_text_ms: components["schemas"]["Millis"];
            first_public_text_ms: components["schemas"]["Millis"];
            ended_ms: components["schemas"]["Millis"];
        };
        ToolTiming: {
            /** @enum {unknown} */
            name: "docs" | "search" | "execute" | null;
            started_ms: components["schemas"]["Millis"];
            ended_ms: components["schemas"]["Millis"];
        };
        AgentTiming: {
            generation_end_ms: components["schemas"]["Millis"];
            save_started_ms: components["schemas"]["Millis"];
            save_finished_ms: components["schemas"]["Millis"];
            final_message_id: number | null;
            final_first_text_ms: components["schemas"]["Millis"];
            models: components["schemas"]["ModelTiming"][];
            tools: components["schemas"]["ToolTiming"][];
        };
        HttpTiming: {
            /** @constant */
            clock: "monotonic_ms_since_http_ingress";
            first_status_ms: components["schemas"]["Millis"];
            first_text_ms: components["schemas"]["Millis"];
            final_first_text_ms: components["schemas"]["Millis"];
            done_ms: components["schemas"]["Millis"];
            agent: components["schemas"]["AgentTiming"] | null;
        };
        ChatStreamEvent: {
            /** @constant */
            type: "start";
            sessionId: string;
        } | {
            /** @constant */
            type: "answer_start";
            messageId: number;
        } | {
            /** @constant */
            type: "text";
            messageId: number;
            contentIndex: number;
            text: string;
        } | {
            /** @constant */
            type: "answer_end";
            messageId: number;
            /** @enum {unknown} */
            state: "generated" | "discarded";
        } | {
            /** @constant */
            type: "tool";
            label: string;
            /** @enum {unknown} */
            state: "running" | "failed" | "done";
        } | {
            /** @constant */
            type: "done";
            sessionId: string;
            turn: components["schemas"]["PublicTurn"];
            timing: components["schemas"]["HttpTiming"];
        } | {
            /** @constant */
            type: "error";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    queryChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    sessionId: string;
                    question: string;
                };
            };
        };
        responses: {
            /** @description NDJSON 流；断连或 error 不表示成功完成。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                };
            };
            /** @description 问题或字段无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Host 或 Origin 不合法 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 会话变化或仍忙碌 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求超过大小上限 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求须为 JSON */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 服务正在关闭 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
